<?php

namespace Database\Seeders;

use App\Models\Network;
use Illuminate\Database\Seeder;

class NetworkSeeder extends Seeder
{
    public function run()
    {
        $countries = [
            ['Hindistan', 'India', 'Индия', 'IND'],
            ['Çin', 'China', 'Китай', 'CHN'],
            ['Amerika Birləşmiş Ştatları', 'United States', 'Соединённые Штаты', 'USA'],
            ['İndoneziya', 'Indonesia', 'Индонезия', 'IDN'],
            ['Pakistan', 'Pakistan', 'Пакистан', 'PAK'],
            ['Nigeriya', 'Nigeria', 'Нигерия', 'NGA'],
            ['Braziliya', 'Brazil', 'Бразилия', 'BRA'],
            ['Banqladeş', 'Bangladesh', 'Бангладеш', 'BGD'],
            ['Rusiya', 'Russia', 'Россия', 'RUS'],
            ['Efiopiya', 'Ethiopia', 'Эфиопия', 'ETH'],
            ['Meksika', 'Mexico', 'Мексика', 'MEX'],
            ['Yaponiya', 'Japan', 'Япония', 'JPN'],
            ['Misir', 'Egypt', 'Египет', 'EGY'],
            ['Filippin', 'Philippines', 'Филиппины', 'PHL'],
            ['Konqo Demokratik Respublikası', 'DR Congo', 'Демократическая Республика Конго', 'COD'],
            ['Vyetnam', 'Vietnam', 'Вьетнам', 'VNM'],
            ['İran', 'Iran', 'Иран', 'IRN'],
            ['Türkiyə', 'Turkey', 'Турция', 'TUR'],
            ['Almaniya', 'Germany', 'Германия', 'DEU'],
            ['Tayland', 'Thailand', 'Таиланд', 'THA'],
            ['Böyük Britaniya', 'United Kingdom', 'Великобритания', 'GBR'],
            ['Tanzaniya', 'Tanzania', 'Танзания', 'TZA'],
            ['Fransa', 'France', 'Франция', 'FRA'],
            ['Cənubi Afrika', 'South Africa', 'Южная Африка', 'ZAF'],
            ['İtaliya', 'Italy', 'Италия', 'ITA'],
            ['Keniya', 'Kenya', 'Кения', 'KEN'],
            ['Myanma', 'Myanmar', 'Мьянма', 'MMR'],
            ['Kolumbiya', 'Colombia', 'Колумбия', 'COL'],
            ['Cənubi Koreya', 'South Korea', 'Южная Корея', 'KOR'],
            ['Sudan', 'Sudan', 'Судан', 'SDN'],
            ['Uqanda', 'Uganda', 'Уганда', 'UGA'],
            ['İspaniya', 'Spain', 'Испания', 'ESP'],
            ['Əlcəzair', 'Algeria', 'Алжир', 'DZA'],
            ['İraq', 'Iraq', 'Ирак', 'IRQ'],
            ['Argentina', 'Argentina', 'Аргентина', 'ARG'],
            ['Əfqanıstan', 'Afghanistan', 'Афганистан', 'AFG'],
            ['Yəmən', 'Yemen', 'Йемен', 'YEM'],
            ['Kanada', 'Canada', 'Канада', 'CAN'],
            ['Polşa', 'Poland', 'Польша', 'POL'],
            ['Mərakeş', 'Morocco', 'Марокко', 'MAR'],
            ['Anqola', 'Angola', 'Ангола', 'AGO'],
            ['Ukrayna', 'Ukraine', 'Украина', 'UKR'],
            ['Özbəkistan', 'Uzbekistan', 'Узбекистан', 'UZB'],
            ['Malayziya', 'Malaysia', 'Малайзия', 'MYS'],
            ['Mozambik', 'Mozambique', 'Мозамбик', 'MOZ'],
            ['Qana', 'Ghana', 'Гана', 'GHA'],
            ['Peru', 'Peru', 'Перу', 'PER'],
            ['Səudiyyə Ərəbistanı', 'Saudi Arabia', 'Саудовская Аравия', 'SAU'],
            ['Madaqaskar', 'Madagascar', 'Мадагаскар', 'MDG'],
            ['Kot-d`İvuar', 'Côte d`Ivoire', 'Кот-д`Ивуар', 'CIV'],
            ['Nepal', 'Nepal', 'Непал', 'NPL'],
            ['Kamerun', 'Cameroon', 'Камерун', 'CMR'],
            ['Venesuela', 'Venezuela', 'Венесуэла', 'VEN'],
            ['Niger', 'Niger', 'Нигер', 'NER'],
            ['Avstraliya', 'Australia', 'Австралия', 'AUS'],
            ['Şimali Koreya', 'North Korea', 'Северная Корея', 'PRK'],
            ['Suriya', 'Syria', 'Сирия', 'SYR'],
            ['Mali', 'Mali', 'Мали', 'MLI'],
            ['Burkina Faso', 'Burkina Faso', 'Буркина-Фасо', 'BFA'],
            ['Şri Lanka', 'Sri Lanka', 'Шри-Ланка', 'LKA'],
            ['Malavi', 'Malawi', 'Малави', 'MWI'],
            ['Zambiya', 'Zambia', 'Замбия', 'ZMB'],
            ['Qazaxıstan', 'Kazakhstan', 'Казахстан', 'KAZ'],
            ['Çad', 'Chad', 'Чад', 'TCD'],
            ['Çili', 'Chile', 'Чили', 'CHL'],
            ['Rumıniya', 'Romania', 'Румыния', 'ROU'],
            ['Somali', 'Somalia', 'Сомали', 'SOM'],
            ['Seneqal', 'Senegal', 'Сенегал', 'SEN'],
            ['Qvatemala', 'Guatemala', 'Гватемала', 'GTM'],
            ['Niderland', 'Netherlands', 'Нидерланды', 'NLD'],
            ['Ekvador', 'Ecuador', 'Эквадор', 'ECU'],
            ['Kamboca', 'Cambodia', 'Камбоджа', 'KHM'],
            ['Zimbabve', 'Zimbabwe', 'Зимбабве', 'ZWE'],
            ['Qvineya', 'Guinea', 'Гвинея', 'GIN'],
            ['Benin', 'Benin', 'Бенин', 'BEN'],
            ['Ruanda', 'Rwanda', 'Руанда', 'RWA'],
            ['Burundi', 'Burundi', 'Бурунди', 'BDI'],
            ['Boliviya', 'Bolivia', 'Боливия', 'BOL'],
            ['Tunis', 'Tunisia', 'Тунис', 'TUN'],
            ['Cənubi Sudan', 'South Sudan', 'Южный Судан', 'SSD'],
            ['Haiti', 'Haiti', 'Гаити', 'HTI'],
            ['Belçika', 'Belgium', 'Бельгия', 'BEL'],
            ['İordaniya', 'Jordan', 'Иордания', 'JOR'],
            ['Dominikan Respublikası', 'Dominican Republic', 'Доминиканская Республика', 'DOM'],
            ['Birləşmiş Ərəb Əmirlikləri', 'United Arab Emirates', 'Объединённые Арабские Эмираты', 'ARE'],
            ['Kuba', 'Cuba', 'Куба', 'CUB'],
            ['Honduras', 'Honduras', 'Гондурас', 'HND'],
            ['Çexiya', 'Czech Republic', 'Чехия', 'CZE'],
            ['İsveç', 'Sweden', 'Швеция', 'SWE'],
            ['Tacikistan', 'Tajikistan', 'Таджикистан', 'TJK'],
            ['Papua Yeni Qvineya', 'Papua New Guinea', 'Папуа – Новая Гвинея', 'PNG'],
            ['Portuqaliya', 'Portugal', 'Португалия', 'PRT'],
            ['Azərbaycan', 'Azerbaijan', 'Азербайджан', 'AZE'],
            ['Yunanıstan', 'Greece', 'Греция', 'GRC'],
            ['Macarıstan', 'Hungary', 'Венгрия', 'HUN'],
            ['Toqo', 'Togo', 'Того', 'TGO'],
            ['İsrail', 'Israel', 'Израиль', 'ISR'],
            ['Avstriya', 'Austria', 'Австрия', 'AUT'],
            ['Belarus', 'Belarus', 'Беларусь', 'BLR'],
            ['İsveçrə', 'Switzerland', 'Швейцария', 'CHE'],
            ['Syerra Leone', 'Sierra Leone', 'Сьерра-Леоне', 'SLE'],
            ['Laos', 'Laos', 'Лаос', 'LAO'],
            ['Türkmənistan', 'Turkmenistan', 'Туркменистан', 'TKM'],
            ['Liviya', 'Libya', 'Ливия', 'LBY'],
            ['Qırğızıstan', 'Kyrgyzstan', 'Киргизия', 'KGZ'],
            ['Paraqvay', 'Paraguay', 'Парагвай', 'PRY'],
            ['Nikaraqua', 'Nicaragua', 'Никарагуа', 'NIC'],
            ['Bolqarıstan', 'Bulgaria', 'Болгария', 'BGR'],
            ['Serbiya', 'Serbia', 'Сербия', 'SRB'],
            ['Salvador', 'El Salvador', 'Сальвадор', 'SLV'],
            ['Konqo', 'Congo', 'Конго', 'COG'],
            ['Danimarka', 'Denmark', 'Дания', 'DNK'],
            ['Sinqapur', 'Singapore', 'Сингапур', 'SGP'],
            ['Livan', 'Lebanon', 'Ливан', 'LBN'],
            ['Finlandiya', 'Finland', 'Финляндия', 'FIN'],
            ['Liberiya', 'Liberia', 'Либерия', 'LBR'],
            ['Norveç', 'Norway', 'Норвегия', 'NOR'],
            ['Slovakiya', 'Slovakia', 'Словакия', 'SVK'],
            ['Fələstin Dövləti', 'State of Palestine', 'Государство Палестина', 'PSE'],
            ['Mərkəzi Afrika Respublikası', 'Central African Republic', 'Центральноафриканская Республика', 'CAF'],
            ['Oman', 'Oman', 'Оман', 'OMN'],
            ['İrlandiya', 'Ireland', 'Ирландия', 'IRL'],
            ['Yeni Zelandiya', 'New Zealand', 'Новая Зеландия', 'NZL'],
            ['Mavritaniya', 'Mauritania', 'Мавритания', 'MRT'],
            ['Kosta Rika', 'Costa Rica', 'Коста-Рика', 'CRI'],
            ['Küveyt', 'Kuwait', 'Кувейт', 'KWT'],
            ['Panama', 'Panama', 'Панама', 'PAN'],
            ['Xorvatiya', 'Croatia', 'Хорватия', 'HRV'],
            ['Gürcüstan', 'Georgia', 'Грузия', 'GEO'],
            ['Eritreya', 'Eritrea', 'Эритрея', 'ERI'],
            ['Monqolustan', 'Mongolia', 'Монголия', 'MNG'],
            ['Uruqvay', 'Uruguay', 'Уругвай', 'URY'],
            ['Bosniya və Herseqovina', 'Bosnia and Herzegovina', 'Босния и Герцеговина', 'BIH'],
            ['Qətər', 'Qatar', 'Катар', 'QAT'],
            ['Moldova', 'Moldova', 'Молдова', 'MDA'],
            ['Namibiya', 'Namibia', 'Намибия', 'NAM'],
            ['Litva', 'Lithuania', 'Литва', 'LTU'],
            ['Yamayka', 'Jamaica', 'Ямайка', 'JAM'],
            ['Albaniya', 'Albania', 'Албания', 'ALB'],
            ['Qambiya', 'Gambia', 'Гамбия', 'GMB'],
            ['Qabon', 'Gabon', 'Габон', 'GAB'],
            ['Botsvana', 'Botswana', 'Ботсвана', 'BWA'],
            ['Lesoto', 'Lesotho', 'Лесото', 'LSO'],
            ['Müqəddəs Taxt-Tac', 'Holy See', 'Святой Престол', 'VAT'],
            ['Qvineya-Bisau', 'Guinea-Bissau', 'Гвинея-Бисау', 'GNB'],
            ['Sloveniya', 'Slovenia', 'Словения', 'SVN'],
            ['Ekvatorial Qvineya', 'Equatorial Guinea', 'Экваториальная Гвинея', 'GNQ'],
            ['Latviya', 'Latvia', 'Латвия', 'LVA'],
            ['Şimali Makedoniya', 'North Macedonia', 'Северная Македония', 'MKD'],
            ['Bəhreyn', 'Bahrain', 'Бахрейн', 'BHR'],
            ['Trinidad və Tobaqo', 'Trinidad and Tobago', 'Тринидад и Тобаго', 'TTO'],
            ['Timor-Leste', 'Timor-Leste', 'Восточный Тимор', 'TLS'],
            ['Estoniya', 'Estonia', 'Эстония', 'EST'],
            ['Kipr', 'Cyprus', 'Кипр', 'CYP'],
            ['Mavriki', 'Mauritius', 'Маврикий', 'MUS'],
            ['Esvatini', 'Eswatini', 'Эсватини', 'SWZ'],
            ['Cibuti', 'Djibouti', 'Джибути', 'DJI'],
            ['Fici', 'Fiji', 'Фиджи', 'FJI'],
            ['Komor Adaları', 'Comoros', 'Коморы', 'COM'],
            ['Qayana', 'Guyana', 'Гайана', 'GUY'],
            ['Solomon Adaları', 'Solomon Islands', 'Соломоновы Острова', 'SLB'],
            ['Butan', 'Bhutan', 'Бутан', 'BTN'],
            ['Lüksemburq', 'Luxembourg', 'Люксембург', 'LUX'],
            ['Monteneqro', 'Montenegro', 'Черногория', 'MNE'],
            ['Surinam', 'Suriname', 'Суринам', 'SUR'],
            ['Malta', 'Malta', 'Мальта', 'MLT'],
            ['Maldivlər', 'Maldives', 'Мальдивы', 'MDV'],
            ['Mikroneziya', 'Micronesia', 'Микронезия', 'FSM'],
            ['Kabo Verde', 'Cabo Verde', 'Кабо-Верде', 'CPV'],
            ['Bruney', 'Brunei', 'Бруней', 'BRN'],
            ['Beliz', 'Belize', 'Белиз', 'BLZ'],
            ['Baham adaları', 'Bahamas', 'Багамские Острова', 'BHS'],
            ['İslandiya', 'Iceland', 'Исландия', 'ISL'],
            ['Vanuatu', 'Vanuatu', 'Вануату', 'VUT'],
            ['Barbados', 'Barbados', 'Барбадос', 'BRB'],
            ['San-Tome və Prinsipi', 'São Tomé and Príncipe', 'Сан-Томе и Принсипи', 'STP'],
            ['Samoa', 'Samoa', 'Самоа', 'WSM'],
            ['Sent-Lusiya', 'Saint Lucia', 'Сент-Люсия', 'LCA'],
            ['Kiribati', 'Kiribati', 'Кирибати', 'KIR'],
            ['Seyşel adaları', 'Seychelles', 'Сейшельские Острова', 'SYC'],
            ['Qrenada', 'Grenada', 'Гренада', 'GRD'],
            ['Tonqa', 'Tonga', 'Тонга', 'TON'],
            ['Sent Vinsent və Qrenadinlər', 'Saint Vincent and the Grenadines', 'Сент-Винсент и Гренадины', 'VCT'],
            ['Antigua və Barbuda', 'Antigua and Barbuda', 'Антигуа и Барбуда', 'ATG'],
            ['Andorra', 'Andorra', 'Андорра', 'AND'],
            ['Dominika', 'Dominica', 'Доминика', 'DMA'],
            ['Sent Kits və Nevis', 'Saint Kitts and Nevis', 'Сент-Китс и Невис', 'KNA'],
            ['Lixtenşteyn', 'Liechtenstein', 'Лихтенштейн', 'LIE'],
            ['Monako', 'Monaco', 'Монако', 'MCO'],
            ['Marşal adaları', 'Marshall Islands', 'Маршалловы Острова', 'MHL'],
            ['San Marino', 'San Marino', 'Сан-Марино', 'SMR'],
            ['Palau', 'Palau', 'Палау', 'PLW'],
            ['Nauru', 'Nauru', 'Науру', 'NRU'],
            ['Tuvalu', 'Tuvalu', 'Тувалу', 'TUV']
        ];

        foreach ($countries as $country) {
            Network::create([
                'name_az' => $country[0],
                'name_en' => $country[1],
                'name_ru' => $country[2],
                'country_code' => $country[3],
                'status' => true
            ]);
        }
    }
} 