<?php

namespace Database\Seeders;

use App\Models\Network;
use Illuminate\Database\Seeder;

class NetworkSeeder extends Seeder
{
    public function run()
    {
        $countries = [
            ['Hindistan', 'India', 'Индия'],
            ['Çin', 'China', 'Китай'],
            ['Amerika Birləşmiş Ştatları', 'United States', 'Соединённые Штаты'],
            ['İndoneziya', 'Indonesia', 'Индонезия'],
            ['Pakistan', 'Pakistan', 'Пакистан'],
            ['Nigeriya', 'Nigeria', 'Нигерия'],
            ['Braziliya', 'Brazil', 'Бразилия'],
            ['Banqladeş', 'Bangladesh', 'Бангладеш'],
            ['Rusiya', 'Russia', 'Россия'],
            ['Efiopiya', 'Ethiopia', 'Эфиопия'],
            ['Meksika', 'Mexico', 'Мексика'],
            ['Yaponiya', 'Japan', 'Япония'],
            ['Misir', 'Egypt', 'Египет'],
            ['Filippin', 'Philippines', 'Филиппины'],
            ['Konqo Demokratik Respublikası', 'DR Congo', 'Демократическая Республика Конго'],
            ['Vyetnam', 'Vietnam', 'Вьетнам'],
            ['İran', 'Iran', 'Иран'],
            ['Türkiyə', 'Turkey', 'Турция'],
            ['Almaniya', 'Germany', 'Германия'],
            ['Tayland', 'Thailand', 'Таиланд'],
            ['Böyük Britaniya', 'United Kingdom', 'Великобритания'],
            ['Tanzaniya', 'Tanzania', 'Танзания'],
            ['Fransa', 'France', 'Франция'],
            ['Cənubi Afrika', 'South Africa', 'Южная Африка'],
            ['İtaliya', 'Italy', 'Италия'],
            ['Keniya', 'Kenya', 'Кения'],
            ['Myanma', 'Myanmar', 'Мьянма'],
            ['Kolumbiya', 'Colombia', 'Колумбия'],
            ['Cənubi Koreya', 'South Korea', 'Южная Корея'],
            ['Sudan', 'Sudan', 'Судан'],
            ['Uqanda', 'Uganda', 'Уганда'],
            ['İspaniya', 'Spain', 'Испания'],
            ['Əlcəzair', 'Algeria', 'Алжир'],
            ['İraq', 'Iraq', 'Ирак'],
            ['Argentina', 'Argentina', 'Аргентина'],
            ['Əfqanıstan', 'Afghanistan', 'Афганистан'],
            ['Yəmən', 'Yemen', 'Йемен'],
            ['Kanada', 'Canada', 'Канада'],
            ['Polşa', 'Poland', 'Польша'],
            ['Mərakeş', 'Morocco', 'Марокко'],
            ['Anqola', 'Angola', 'Ангола'],
            ['Ukrayna', 'Ukraine', 'Украина'],
            ['Özbəkistan', 'Uzbekistan', 'Узбекистан'],
            ['Malayziya', 'Malaysia', 'Малайзия'],
            ['Mozambik', 'Mozambique', 'Мозамбик'],
            ['Qana', 'Ghana', 'Гана'],
            ['Peru', 'Peru', 'Перу'],
            ['Səudiyyə Ərəbistanı', 'Saudi Arabia', 'Саудовская Аравия'],
            ['Madaqaskar', 'Madagascar', 'Мадагаскар'],
            ['Kot-d`İvuar', 'Côte d`Ivoire', 'Кот-д`Ивуар'],
            ['Nepal', 'Nepal', 'Непал'],
            ['Kamerun', 'Cameroon', 'Камерун'],
            ['Venesuela', 'Venezuela', 'Венесуэла'],
            ['Niger', 'Niger', 'Нигер'],
            ['Avstraliya', 'Australia', 'Австралия'],
            ['Şimali Koreya', 'North Korea', 'Северная Корея'],
            ['Suriya', 'Syria', 'Сирия'],
            ['Mali', 'Mali', 'Мали'],
            ['Burkina Faso', 'Burkina Faso', 'Буркина-Фасо'],
            ['Şri Lanka', 'Sri Lanka', 'Шри-Ланка'],
            ['Malavi', 'Malawi', 'Малави'],
            ['Zambiya', 'Zambia', 'Замбия'],
            ['Qazaxıstan', 'Kazakhstan', 'Казахстан'],
            ['Çad', 'Chad', 'Чад'],
            ['Çili', 'Chile', 'Чили'],
            ['Rumıniya', 'Romania', 'Румыния'],
            ['Somali', 'Somalia', 'Сомали'],
            ['Seneqal', 'Senegal', 'Сенегал'],
            ['Qvatemala', 'Guatemala', 'Гватемала'],
            ['Niderland', 'Netherlands', 'Нидерланды'],
            ['Ekvador', 'Ecuador', 'Эквадор'],
            ['Kamboca', 'Cambodia', 'Камбоджа'],
            ['Zimbabve', 'Zimbabwe', 'Зимбабве'],
            ['Qvineya', 'Guinea', 'Гвинея'],
            ['Benin', 'Benin', 'Бенин'],
            ['Ruanda', 'Rwanda', 'Руанда'],
            ['Burundi', 'Burundi', 'Бурунди'],
            ['Boliviya', 'Bolivia', 'Боливия'],
            ['Tunis', 'Tunisia', 'Тунис'],
            ['Cənubi Sudan', 'South Sudan', 'Южный Судан'],
            ['Haiti', 'Haiti', 'Гаити'],
            ['Belçika', 'Belgium', 'Бельгия'],
            ['İordaniya', 'Jordan', 'Иордания'],
            ['Dominikan Respublikası', 'Dominican Republic', 'Доминиканская Республика'],
            ['Birləşmiş Ərəb Əmirlikləri', 'United Arab Emirates', 'Объединённые Арабские Эмираты'],
            ['Kuba', 'Cuba', 'Куба'],
            ['Honduras', 'Honduras', 'Гондурас'],
            ['Çexiya', 'Czech Republic', 'Чехия'],
            ['İsveç', 'Sweden', 'Швеция'],
            ['Tacikistan', 'Tajikistan', 'Таджикистан'],
            ['Papua Yeni Qvineya', 'Papua New Guinea', 'Папуа – Новая Гвинея'],
            ['Portuqaliya', 'Portugal', 'Португалия'],
            ['Azərbaycan', 'Azerbaijan', 'Азербайджан'],
            ['Yunanıstan', 'Greece', 'Греция'],
            ['Macarıstan', 'Hungary', 'Венгрия'],
            ['Toqo', 'Togo', 'Того'],
            ['İsrail', 'Israel', 'Израиль'],
            ['Avstriya', 'Austria', 'Австрия'],
            ['Belarus', 'Belarus', 'Беларусь'],
            ['İsveçrə', 'Switzerland', 'Швейцария'],
            ['Syerra Leone', 'Sierra Leone', 'Сьерра-Леоне'],
            ['Laos', 'Laos', 'Лаос'],
            ['Türkmənistan', 'Turkmenistan', 'Туркменистан'],
            ['Liviya', 'Libya', 'Ливия'],
            ['Qırğızıstan', 'Kyrgyzstan', 'Киргизия'],
            ['Paraqvay', 'Paraguay', 'Парагвай'],
            ['Nikaraqua', 'Nicaragua', 'Никарагуа'],
            ['Bolqarıstan', 'Bulgaria', 'Болгария'],
            ['Serbiya', 'Serbia', 'Сербия'],
            ['Salvador', 'El Salvador', 'Сальвадор'],
            ['Konqo', 'Congo', 'Конго'],
            ['Danimarka', 'Denmark', 'Дания'],
            ['Sinqapur', 'Singapore', 'Сингапур'],
            ['Livan', 'Lebanon', 'Ливан'],
            ['Finlandiya', 'Finland', 'Финляндия'],
            ['Liberiya', 'Liberia', 'Либерия'],
            ['Norveç', 'Norway', 'Норвегия'],
            ['Slovakiya', 'Slovakia', 'Словакия'],
            ['Fələstin Dövləti', 'State of Palestine', 'Государство Палестина'],
            ['Mərkəzi Afrika Respublikası', 'Central African Republic', 'Центральноафриканская Республика'],
            ['Oman', 'Oman', 'Оман'],
            ['İrlandiya', 'Ireland', 'Ирландия'],
            ['Yeni Zelandiya', 'New Zealand', 'Новая Зеландия'],
            ['Mavritaniya', 'Mauritania', 'Мавритания'],
            ['Kosta Rika', 'Costa Rica', 'Коста-Рика'],
            ['Küveyt', 'Kuwait', 'Кувейт'],
            ['Panama', 'Panama', 'Панама'],
            ['Xorvatiya', 'Croatia', 'Хорватия'],
            ['Gürcüstan', 'Georgia', 'Грузия'],
            ['Eritreya', 'Eritrea', 'Эритрея'],
            ['Monqolustan', 'Mongolia', 'Монголия'],
            ['Uruqvay', 'Uruguay', 'Уругвай'],
            ['Bosniya və Herseqovina', 'Bosnia and Herzegovina', 'Босния и Герцеговина'],
            ['Qətər', 'Qatar', 'Катар'],
            ['Moldova', 'Moldova', 'Молдова'],
            ['Namibiya', 'Namibia', 'Намибия'],
            ['Ermənistan', 'Armenia', 'Армения'],
            ['Litva', 'Lithuania', 'Литва'],
            ['Yamayka', 'Jamaica', 'Ямайка'],
            ['Albaniya', 'Albania', 'Албания'],
            ['Qambiya', 'Gambia', 'Гамбия'],
            ['Qabon', 'Gabon', 'Габон'],
            ['Botsvana', 'Botswana', 'Ботсвана'],
            ['Lesoto', 'Lesotho', 'Лесото'],
            ['Müqəddəs Taxt-Tac', 'Holy See', 'Святой Престол'],
            ['Qvineya-Bisau', 'Guinea-Bissau', 'Гвинея-Бисау'],
            ['Sloveniya', 'Slovenia', 'Словения'],
            ['Ekvatorial Qvineya', 'Equatorial Guinea', 'Экваториальная Гвинея'],
            ['Latviya', 'Latvia', 'Латвия'],
            ['Şimali Makedoniya', 'North Macedonia', 'Северная Македония'],
            ['Bəhreyn', 'Bahrain', 'Бахрейн'],
            ['Trinidad və Tobaqo', 'Trinidad and Tobago', 'Тринидад и Тобаго'],
            ['Timor-Leste', 'Timor-Leste', 'Восточный Тимор'],
            ['Estoniya', 'Estonia', 'Эстония'],
            ['Kipr', 'Cyprus', 'Кипр'],
            ['Mavriki', 'Mauritius', 'Маврикий'],
            ['Esvatini', 'Eswatini', 'Эсватини'],
            ['Cibuti', 'Djibouti', 'Джибути'],
            ['Fici', 'Fiji', 'Фиджи'],
            ['Komor Adaları', 'Comoros', 'Коморы'],
            ['Qayana', 'Guyana', 'Гайана'],
            ['Solomon Adaları', 'Solomon Islands', 'Соломоновы Острова'],
            ['Butan', 'Bhutan', 'Бутан'],
            ['Lüksemburq', 'Luxembourg', 'Люксембург'],
            ['Monteneqro', 'Montenegro', 'Черногория'],
            ['Surinam', 'Suriname', 'Суринам'],
            ['Malta', 'Malta', 'Мальта'],
            ['Maldivlər', 'Maldives', 'Мальдивы'],
            ['Mikroneziya', 'Micronesia', 'Микронезия'],
            ['Kabo Verde', 'Cabo Verde', 'Кабо-Верде'],
            ['Bruney', 'Brunei', 'Бруней'],
            ['Beliz', 'Belize', 'Белиз'],
            ['Baham adaları', 'Bahamas', 'Багамские Острова'],
            ['İslandiya', 'Iceland', 'Исландия'],
            ['Vanuatu', 'Vanuatu', 'Вануату'],
            ['Barbados', 'Barbados', 'Барбадос'],
            ['San-Tome və Prinsipi', 'São Tomé and Príncipe', 'Сан-Томе и Принсипи'],
            ['Samoa', 'Samoa', 'Самоа'],
            ['Sent-Lusiya', 'Saint Lucia', 'Сент-Люсия'],
            ['Kiribati', 'Kiribati', 'Кирибати'],
            ['Seyşel adaları', 'Seychelles', 'Сейшельские Острова'],
            ['Qrenada', 'Grenada', 'Гренада'],
            ['Tonqa', 'Tonga', 'Тонга'],
            ['Sent Vinsent və Qrenadinlər', 'Saint Vincent and the Grenadines', 'Сент-Винсент и Гренадины'],
            ['Antigua və Barbuda', 'Antigua and Barbuda', 'Антигуа и Барбуда'],
            ['Andorra', 'Andorra', 'Андорра'],
            ['Dominika', 'Dominica', 'Доминика'],
            ['Sent Kits və Nevis', 'Saint Kitts and Nevis', 'Сент-Китс и Невис'],
            ['Lixtenşteyn', 'Liechtenstein', 'Лихтенштейн'],
            ['Monako', 'Monaco', 'Монако'],
            ['Marşal adaları', 'Marshall Islands', 'Маршалловы Острова'],
            ['San Marino', 'San Marino', 'Сан-Марино'],
            ['Palau', 'Palau', 'Палау'],
            ['Nauru', 'Nauru', 'Науру'],
            ['Tuvalu', 'Tuvalu', 'Тувалу']
        ];

        foreach ($countries as $country) {
            Network::create([
                'name_az' => $country[0],
                'name_en' => $country[1],
                'name_ru' => $country[2],
                'status' => true

            ]);
        }
    }
} 